adjective = input("Enter an adjective: ")
adjective2 = input("Enter another adjective: ")
type_of_bird = input("Enter a type of bird: ")
room = input("Enter a room: ")
verb = input("Enter a past tense verb: ")
verb2 = input("Enter a verb: ")
relative = input("Enter a relatives name: ")
noun = input("Enter a noun: ")
liquid = input("Enter a type of liquid: ")
verb3 = input("Enter a verb ending with ing: ")
body_part = input("Enter a body part: ")
noun2 = input("Enter a plural noun: ")
verb4 = input("Enter a verb ending with ing: ")
noun3 = input("Enter a noun: ")

print("It was a " + adjective + ", cold November day.")
print("I woke up to the " + adjective2 + " smell of " + type_of_bird \
+ " roasting in the " + room + " downstairs." )
